/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.afarcloud.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum CommandType implements org.apache.thrift.TEnum {
  NAV_TAKEOFF(1),
  NAV_LAND(2),
  NAV_WAYPOINT(3),
  CAMERA_IMAGE(4),
  VIDEO_START_CAPTURE(5),
  VIDEO_STOP_CAPTURE(6),
  NAV_HOTPOINT(7),
  NAV_FOLLOW_TARGET(8),
  NAV_TRACK_SUBJECT(9),
  CAMERA_PANORAMA(10),
  NAV_HOME(11);

  private final int value;

  private CommandType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static CommandType findByValue(int value) { 
    switch (value) {
      case 1:
        return NAV_TAKEOFF;
      case 2:
        return NAV_LAND;
      case 3:
        return NAV_WAYPOINT;
      case 4:
        return CAMERA_IMAGE;
      case 5:
        return VIDEO_START_CAPTURE;
      case 6:
        return VIDEO_STOP_CAPTURE;
      case 7:
        return NAV_HOTPOINT;
      case 8:
        return NAV_FOLLOW_TARGET;
      case 9:
        return NAV_TRACK_SUBJECT;
      case 10:
        return CAMERA_PANORAMA;
      case 11:
        return NAV_HOME;
      default:
        return null;
    }
  }
}
