/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.afarcloud.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ObservationType implements org.apache.thrift.TEnum {
  air_flow(0),
  air_humidity(1),
  air_pressure(2),
  air_temperature(3),
  altitude(4),
  application_rate_mm3_m2(5),
  battery(6),
  crude_protein(7),
  condensed_work_state(8),
  co2(9),
  dry_matter(10),
  d_value(11),
  electrical_conductivity_bulk(12),
  electrical_conductivity_pores(13),
  engine_percentage_torque(14),
  engine_speed(15),
  engine_total_hours_of_operation(16),
  fuel_ratio(17),
  fibre(18),
  filter_fouling_level_F7(19),
  filter_fouling_level_G4(20),
  filter_fouling_level_H13(21),
  irrigation(22),
  latitude(23),
  longitude(24),
  protein(25),
  pmr_in_1d(26),
  pmr_in_2d(27),
  pmr_in_3d(28),
  pmr_in_4d(29),
  pmr_in_5d(30),
  powdery_mildew_risk(31),
  relative_dielectric_constant(32),
  rainfall(33),
  rainfall_gain(34),
  soil_humidity(35),
  soil_matrix_potential(36),
  soil_temperature(37),
  solar_radiation(38),
  speed(39),
  signal_strength(40),
  status(41),
  temperature_teros12(42),
  temperature_teros21(43),
  total_fuel_used(44),
  vehicle_speed(45),
  volumetric_water_content_mineral_soil(46),
  water_consumption(47),
  wind_direction(48),
  wind_gain(49),
  wind_speed(50);

  private final int value;

  private ObservationType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ObservationType findByValue(int value) { 
    switch (value) {
      case 0:
        return air_flow;
      case 1:
        return air_humidity;
      case 2:
        return air_pressure;
      case 3:
        return air_temperature;
      case 4:
        return altitude;
      case 5:
        return application_rate_mm3_m2;
      case 6:
        return battery;
      case 7:
        return crude_protein;
      case 8:
        return condensed_work_state;
      case 9:
        return co2;
      case 10:
        return dry_matter;
      case 11:
        return d_value;
      case 12:
        return electrical_conductivity_bulk;
      case 13:
        return electrical_conductivity_pores;
      case 14:
        return engine_percentage_torque;
      case 15:
        return engine_speed;
      case 16:
        return engine_total_hours_of_operation;
      case 17:
        return fuel_ratio;
      case 18:
        return fibre;
      case 19:
        return filter_fouling_level_F7;
      case 20:
        return filter_fouling_level_G4;
      case 21:
        return filter_fouling_level_H13;
      case 22:
        return irrigation;
      case 23:
        return latitude;
      case 24:
        return longitude;
      case 25:
        return protein;
      case 26:
        return pmr_in_1d;
      case 27:
        return pmr_in_2d;
      case 28:
        return pmr_in_3d;
      case 29:
        return pmr_in_4d;
      case 30:
        return pmr_in_5d;
      case 31:
        return powdery_mildew_risk;
      case 32:
        return relative_dielectric_constant;
      case 33:
        return rainfall;
      case 34:
        return rainfall_gain;
      case 35:
        return soil_humidity;
      case 36:
        return soil_matrix_potential;
      case 37:
        return soil_temperature;
      case 38:
        return solar_radiation;
      case 39:
        return speed;
      case 40:
        return signal_strength;
      case 41:
        return status;
      case 42:
        return temperature_teros12;
      case 43:
        return temperature_teros21;
      case 44:
        return total_fuel_used;
      case 45:
        return vehicle_speed;
      case 46:
        return volumetric_water_content_mineral_soil;
      case 47:
        return water_consumption;
      case 48:
        return wind_direction;
      case 49:
        return wind_gain;
      case 50:
        return wind_speed;
      default:
        return null;
    }
  }
}
