/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.afarcloud.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum TaskType implements org.apache.thrift.TEnum {
  TRANSIT(0),
  SURVEY(1),
  INSPECT(2),
  HOTPOINT(3),
  FOLLOW_TARGET(4),
  ACTIVE_TRACK(5),
  PANORAMA(6);

  private final int value;

  private TaskType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TaskType findByValue(int value) { 
    switch (value) {
      case 0:
        return TRANSIT;
      case 1:
        return SURVEY;
      case 2:
        return INSPECT;
      case 3:
        return HOTPOINT;
      case 4:
        return FOLLOW_TARGET;
      case 5:
        return ACTIVE_TRACK;
      case 6:
        return PANORAMA;
      default:
        return null;
    }
  }
}
